### PR TITLE
Add run time permissions on Android

### PR DESCRIPTION
**Pull request by Ansalibrahim**
- Updated RNSoundRecorderModule with run time permissions.

### CODE REVIEW

**Comment by kevinresol** [comment]
Is this consistent with iOS?

**Comment by Ansalibrahim** [comment]
iOS already shows permissions when we try to access the mic. So no conflict with iOS app.

**Comment by kevinresol** [comment]
Ok, can you undo the white space changes and force push again? I don't want to mess up the blame history.

**Comment by Ansalibrahim** [comment]
@kevinresol Please check now.

**Comment by kevinresol** [comment]
Thanks!

**Comment by ansal-exp** [comment]
@kevinresol, when does this, will get published on NPM? The latest version 1.3.3 does not contain these changes.

**Comment by kevinresol** [comment]
This is now reverted. Please request permissions manually.

**Pull request merged**
